/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mungo_harmony_BufferUtils */

#ifndef _Included_com_mungo_harmony_BufferUtils
#define _Included_com_mungo_harmony_BufferUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyByteBufferToByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyByteBufferToByteBuffer
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    FastCopyArrayToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_FastCopyArrayToByteBuffer___3FLjava_nio_ByteBuffer_2III
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    FastCopyArrayToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_FastCopyArrayToByteBuffer___3ILjava_nio_ByteBuffer_2III
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyFloatsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyFloatsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyFloatsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyFloatsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyFloatsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyFloatsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyFloatsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyFloatsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyIntsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyIntsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyIntsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyIntsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyIntsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyIntsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyIntsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyIntsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyShortsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyShortsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyShortsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyShortsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyShortsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyShortsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyShortsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyShortsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUShortsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUShortsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUShortsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUShortsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUShortsToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUShortsToByteBuffer___3ILjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUShortsToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUShortsToByteBuffer___3FLjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyBytesToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyBytesToByteBuffer___3ILjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyBytesToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyBytesToByteBuffer___3FLjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyBytesToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyBytesToByteBuffer___3ILjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyBytesToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyBytesToByteBuffer___3FLjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUBytesToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUBytesToByteBuffer___3ILjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUBytesToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUBytesToByteBuffer___3FLjava_nio_ByteBuffer_2IIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUBytesToByteBuffer
 * Signature: ([ILjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUBytesToByteBuffer___3ILjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jintArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyUBytesToByteBuffer
 * Signature: ([FLjava/nio/ByteBuffer;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyUBytesToByteBuffer___3FLjava_nio_ByteBuffer_2IIIIII
  (JNIEnv *, jclass, jfloatArray, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyFloatsFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;[FIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyFloatsFromByteBuffer
  (JNIEnv *, jclass, jobject, jfloatArray, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyIntsFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;[IIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyIntsFromByteBuffer
  (JNIEnv *, jclass, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyShortsFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;[IIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyShortsFromByteBuffer
  (JNIEnv *, jclass, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_mungo_harmony_BufferUtils
 * Method:    CopyBytesFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;[IIII)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_BufferUtils_CopyBytesFromByteBuffer
  (JNIEnv *, jclass, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
