/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mungo_harmony_NHGL */

#ifndef _Included_com_mungo_harmony_NHGL
#define _Included_com_mungo_harmony_NHGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glBufferData
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glBufferData
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glBufferSubData
 * Signature: (III[F)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glBufferSubData__III_3F
  (JNIEnv *, jclass, jint, jint, jint, jfloatArray);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glBufferSubData
 * Signature: (IIII[F)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glBufferSubData__IIII_3F
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloatArray);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixels
 * Signature: (IIIIII[I)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixels__IIIIII_3I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixels
 * Signature: (IIIIII[III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixels__IIIIII_3III
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jint, jint);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixels32
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixels32__IIII_3I
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixels32
 * Signature: (IIII[III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixels32__IIII_3III
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray, jint, jint);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixelsFlipped
 * Signature: (IIIIII[I)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixelsFlipped__IIIIII_3I
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixelsFlipped
 * Signature: (IIIIII[III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixelsFlipped__IIIIII_3III
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jint, jint);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixelsFlipped32
 * Signature: (IIII[I)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixelsFlipped32__IIII_3I
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glReadPixelsFlipped32
 * Signature: (IIII[III)V
 */
JNIEXPORT void JNICALL Java_com_mungo_harmony_NHGL_glReadPixelsFlipped32__IIII_3III
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray, jint, jint);

/*
 * Class:     com_mungo_harmony_NHGL
 * Method:    glGetActiveUniform
 * Signature: (II[I[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mungo_harmony_NHGL_glGetActiveUniform
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
