/**********************************************************************
 * Extern for Clipboard
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Clipboard = function () {};
Clipboard.prototype = {
  "emit": function () {},
  "off": function () {},
  "on": function () {},
  "once": function () {}
};
/**********************************************************************
 * End Generated Extern for Clipboard
/**********************************************************************/